default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bar_development

test:
  <<: *default
  database: bar_test

production:
  <<: *default
  database: bar_production
